server:
  session-timeout: 1800
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /


# Spring 配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    #禁用缓存
    cache: false
  profiles:
    active: dev

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**/*Mapper.xml
  typeAliasesPackage: com.ming.upms.**.domain